name: task_1
description: "Aplicativo de gerenciamento de tarefas - Tarefa 1"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.4
  extended_text: ^14.1.0
  uuid: ^4.5.0
  rive: ^0.13.14
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/magazord_logo.png
    - assets/animations/loading.riv

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/magazord_logo.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
