name: task_2
description: "Aplicativo de gerenciamento de tarefas - Tarefa 1"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  extended_text: ^14.1.0
  uuid: ^4.5.0
  rive: ^0.13.14
  font_awesome_flutter: ^10.8.0
  reactive_forms: ^17.0.1
  geolocator: ^13.0.2
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  weather_icons: ^3.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/magazord_logo.png
    - assets/animations/day_to_night_switch.riv
    - assets/animations/rain.riv
    - assets/animations/day_and_night_switch_button.riv
